### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by krschultz** [geon/geon.github.com#1]
Very impressed & interested in your post about Dyslexia. I don't see a LICENSE on this repo so I was wondering what your preference was if I were to fork it and play with it a bit.

**Comment by atalan** [comment]
+1 !
We would like to do the same demo in French.

**Comment by frankmeeuwsen** [comment]
I took the liberty of forking it and make a Dutch translation. You can check it on http://frankmeeuwsen.github.io/Dsxyliea/. The last couple of days it got quite a bit of attention on Facebook and Twitter and some online media as well. Of course I refer to your original article.

**Comment by geon** [comment]
@krschultz (Or anyone else reading) You are welcome to do whatever you like with the JS code.

@frankmeeuwsen : Cool! No problem.

I suppose I should create a separate repo with a LICENSE for it, instead of having it bundled with my blog.
